# Generated by Django 4.2.11 on 2024-06-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funfun', '0004_alter_comment_user_alter_investment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
